In [1]:
import numpy as np

In [2]:
np?

In [3]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [4]:
np.array([2.5,3,4,5])

array([2.5, 3. , 4. , 5. ])

In [5]:
%%timeit
l1=list(range(5000000))
l2=list(range(5000000))

678 ms ± 67.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
%%timeit
np_array1=np.arange(5000000)
np_array2=np.arange(5000000)

52.6 ms ± 5.62 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [11]:
%%timeit
np.array([2.5,3,4,5])

5.61 µs ± 54.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [18]:
from numpy import array
from numpy import mean
v=array([1,2,3,4,5,6])
print(v)
result=mean(v)
print(result)

[1 2 3 4 5 6]
3.5


In [19]:
v=array([1,2,3,4,5,6])
v

array([1, 2, 3, 4, 5, 6])

In [20]:
v=array([1,2,3,4,5,6])
print(v)

[1 2 3 4 5 6]


In [24]:
from numpy import array
from numpy import var
v=array([1,2,3,4,5,6])
print(v)
result=var(v,ddof=1)
print(result)

[1 2 3 4 5 6]
3.5


In [26]:
from numpy import array
from numpy import cov
x=([1,2,3,4,5,6,7,8,9])
print(x)
y=([9,8,7,6,5,4,3,2,1])
print(y)
result=cov(x,y)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
[[ 7.5 -7.5]
 [-7.5  7.5]]


In [31]:
from numpy import array
from numpy import cov
x=([1,2,3,4,5,6,7,8,9])
print(x)
y=([9,8,7,6,5,4,3,2,1])
print(y)
result=cov(x,y)[1,0]
result

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1]


-7.5

# Working with pandas package

In [32]:
import pandas as pd

In [33]:
s=pd.Series([1,2,3,np.nan,5,6],index=['A','B','C','D','E','F'])
print(s)

A    1.0
B    2.0
C    3.0
D    NaN
E    5.0
F    6.0
dtype: float64


In [34]:
data={'Gender':['f','m','m'],'Emp_ID':['E01','E02','E03'],'Age':[25,27,25]}

In [35]:
data

{'Gender': ['f', 'm', 'm'],
 'Emp_ID': ['E01', 'E02', 'E03'],
 'Age': [25, 27, 25]}

In [36]:
df=pd.DataFrame(data,columns=['Emp_ID','Gender','Age'])

In [37]:
df

Emp_ID Gender  Age
0    E01      f   25
1    E02      m   27
2    E03      m   25